keys:
     client_id: "your_client_id"
     secret_key: "your_secret_key1"
notes:
     published_dir: "/var/www/slip/published"
     draft_dir: "/var/www/slip/draft"
     archived_dir: "/var/www/slip/archived"
     deleted_dir: "/var/www/slip/deleted"
     private_dir: "/var/www/slip/private"
     default_author: "slip"
     default_status: "draft"
     default_tags: ["slip"]